apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-blue
spec:
  replicas: {{ .Values.blue.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
      app.kubernetes.io/instance: {{ .Release.Name }}
      slot: blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
        app.kubernetes.io/instance: {{ .Release.Name }}
        slot: blue
    spec:
      containers:
        - name: http-echo
          image: "{{ .Values.blue.image }}"
          imagePullPolicy: {{ .Values.blue.pullPolicy }}
          args: ["-text=Blue Deployment"]
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
          readinessProbe:
            httpGet:
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi