apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: echo
    slot: {{ .Values.productionSlot}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
